line_length:
  warning: 300 # 当一行超过300个字的时候给出警告
type_body_length:
  warning: 500 # body中超过500行的时候给出警告
file_length:
  warning: 750 # 一页超过750行的时候给出警告
  
opt_in_rules: # 开启一些默认不开启的规则
  - explicit_init # 禁止你在初始化结构体或类时，写出多余的 .init()
  - empty_count # 当你想判断数组是否为空时，推荐使用 .isEmpty，而不是 .count == 0
  - fatal_error_message # 要求 fatalError() 必须有清晰的错误信息，不能传空字符串或省略
  - redundant_optional_initialization # 检测是否多余地初始化为 nil，因为 Swift 默认初始化为 nil（可选值）。
  - operator_usage_whitespace # 要求运算符两侧有空格，提高代码可读性
  
disabled_rules:
  - trailing_whitespace 

